import { PageHeader } from "@/components/layout/PageHeader";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";
import { createPageMetadata } from "@/lib/metadata";
import { StructuredData } from "@/components/seo/StructuredData";
import { getBreadcrumbSchema } from "@/lib/structured-data";

export const metadata = createPageMetadata({
  title: "Editorial Policy",
  description:
    "CalcLume editorial standards for content review, AI-assisted drafting, corrections, and localization.",
  path: "/editorial-policy/",
});

export default function EditorialPolicyPage() {
  const breadcrumbs = [
    { name: "Home", path: "/" },
    { name: "Editorial Policy", path: "/editorial-policy/" },
  ];

  return (
    <>
      <StructuredData data={getBreadcrumbSchema(breadcrumbs)} />
      <PageHeader
        title="Editorial Policy"
        description="Standards for how CalcLume creates, reviews, and maintains its content."
        breadcrumbs={breadcrumbs}
      />
      <Section>
        <Container>
          <div className="prose-content max-w-3xl">
            <h2>Human review requirements</h2>
            <p>
              All published calculator pages and trust content undergo human
              review before publication. Reviewers verify formula accuracy,
              step correctness, interpretation clarity, and accessibility
              compliance.
            </p>

            <h2>AI-assisted drafting boundaries</h2>
            <p>
              AI tools may assist with drafting explanatory text, generating
              test cases, or structuring step sequences. However, all formulas,
              calculations, source citations, and factual claims are verified by
              a human reviewer. AI-generated content is never published without
              human verification.
            </p>

            <h2>No fabricated sources</h2>
            <p>
              CalcLume does not invent citations, authors, expert reviewers,
              search volume data, or usage statistics. Every source listed on a
              calculator page must be a real reference that was consulted during
              development.
            </p>

            <h2>Content updates</h2>
            <p>
              Trust pages and calculator content are reviewed periodically.
              Material changes are noted with an updated date. Minor copy
              improvements may be made without a formal version notice.
            </p>

            <h2>Correction handling</h2>
            <p>
              Reported errors are investigated within a reasonable timeframe.
              Confirmed errors are corrected, and the affected page is updated
              with a correction note and revised last-reviewed date.
            </p>

            <h2>Calculator and content separation</h2>
            <p>
              Calculator logic and editorial content are maintained separately.
              Calculation code is tested independently of surrounding
              explanatory text. Marketing copy does not override or obscure
              calculator functionality.
            </p>

            <h2>Localization standards</h2>
            <p>
              English is the first launch language. Future Arabic localization
              will be curated by human translators — not generated by automatic
              mass translation. The site architecture supports locale-specific
              routes without requiring a CMS or database.
            </p>
          </div>
        </Container>
      </Section>
    </>
  );
}
